#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  CONFIG_REGISTRY,
  listPublicRuntimeConfigKeys,
  listWorkerDynamicConfigEntries,
  validateConfigRegistry,
} from '../../shared/src/contracts/config-registry.js';

const __filename = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(__filename), '..', '..');

const generatedFiles = [
  ['docs/generated/config-registry.snapshot.json', renderRegistrySnapshot],
  ['docs/generated/env-contract.generated.md', renderEnvContract],
  ['docs/generated/frontend-public-config.generated.json', renderFrontendPublicConfig],
  ['docs/generated/worker-dynamic-config-allowlist.generated.json', renderWorkerDynamicAllowlist],
  ['docs/generated/worker-secret-matrix.generated.json', renderWorkerSecretMatrix],
  ['docs/generated/github-secrets-checklist.generated.md', renderGithubSecretsChecklist],
  ['docs/generated/wrangler-secret-put.generated.md', renderWranglerSecretDocs],
  ['backend/src/config/schema.generated.fragment.js', renderBackendSchemaFragment],
  ['backend/src/config/admin-ui-schema.generated.json', renderAdminUiSchema],
  ['k3s/configmap.generated.yaml', renderK3sConfigMap],
  ['k3s/secret.example.generated.yaml', renderK3sSecretExample],
];

function json(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function header(kind = 'text') {
  if (kind === 'js') return '// DO NOT EDIT: generated by tools/config-registry/generate.mjs\n';
  if (kind === 'yaml') return '# DO NOT EDIT: generated by tools/config-registry/generate.mjs\n';
  if (kind === 'md') return '<!-- DO NOT EDIT: generated by tools/config-registry/generate.mjs -->\n';
  return '';
}

function renderRegistrySnapshot() {
  return json({
    generatedBy: 'tools/config-registry/generate.mjs',
    valueCollection: false,
    totalKeys: CONFIG_REGISTRY.length,
    keys: CONFIG_REGISTRY,
  });
}

function renderEnvContract() {
  const lines = [
    '# Environment Contract',
    '',
    header('md').trim(),
    '',
    '| Key | Classification | Owner | Scopes | Delivery | Required In | Public | Runtime Mutable | Rotation |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
  ];
  for (const item of [...CONFIG_REGISTRY].sort((a, b) => a.key.localeCompare(b.key))) {
    lines.push(
      `| \`${item.key}\` | ${item.classification} | ${item.owner} | ${item.scopes.join(', ')} | ${item.delivery.join(', ')} | ${item.requiredIn.join(', ') || '-'} | ${item.publicExposure ? 'yes' : 'no'} | ${item.mutableAtRuntime ? 'yes' : 'no'} | ${item.rotation} |`,
    );
  }
  lines.push('');
  return lines.join('\n');
}

function renderFrontendPublicConfig() {
  return json({
    generatedBy: 'tools/config-registry/generate.mjs',
    publicRuntimeKeys: listPublicRuntimeConfigKeys().sort(),
    deniedBrowserSecretKeys: CONFIG_REGISTRY.filter(
      (item) => item.scopes.includes('frontend') && item.classification === 'secret',
    ).map((item) => item.key),
  });
}

function renderWorkerDynamicAllowlist() {
  return json({
    generatedBy: 'tools/config-registry/generate.mjs',
    keys: listWorkerDynamicConfigEntries()
      .map((item) => ({
        key: item.key,
        classification: item.classification,
        scopes: item.scopes,
        delivery: item.delivery,
      }))
      .sort((a, b) => a.key.localeCompare(b.key)),
  });
}

function renderWorkerSecretMatrix() {
  const workerScopes = ['api-gateway', 'r2-gateway', 'seo-gateway', 'terminal-gateway'];
  const usesSecretDelivery = (item) =>
    item.classification === 'secret' ||
    item.delivery.includes('github-secret') ||
    item.delivery.includes('wrangler-secret');
  const include = workerScopes.map((scope) => {
    const entries = CONFIG_REGISTRY.filter((item) => item.scopes.includes(scope));
    return {
      id: scope,
      requiredSecrets: entries
        .filter((item) => usesSecretDelivery(item) && item.requiredIn.includes(scope))
        .map((item) => item.key)
        .sort(),
      optionalSecrets: entries
        .filter((item) => usesSecretDelivery(item) && !item.requiredIn.includes(scope))
        .map((item) => item.key)
        .sort(),
      vars: entries
        .filter((item) => item.classification !== 'secret')
        .map((item) => item.key)
        .sort(),
    };
  });
  return json({ generatedBy: 'tools/config-registry/generate.mjs', include });
}

function renderGithubSecretsChecklist() {
  const keys = CONFIG_REGISTRY.filter((item) => item.delivery.includes('github-secret'))
    .map((item) => item.key)
    .sort();
  return [
    '# GitHub Secrets Checklist',
    '',
    header('md').trim(),
    '',
    ...keys.map((key) => `- [ ] \`${key}\``),
    '',
  ].join('\n');
}

function renderWranglerSecretDocs() {
  const keys = CONFIG_REGISTRY.filter((item) => item.delivery.includes('wrangler-secret'))
    .map((item) => item.key)
    .sort();
  return [
    '# Wrangler Secret Commands',
    '',
    header('md').trim(),
    '',
    'Run with the intended Worker environment selected. Values are read interactively by Wrangler.',
    '',
    ...keys.map((key) => `- \`wrangler secret put ${key}\``),
    '',
  ].join('\n');
}

function renderBackendSchemaFragment() {
  const keys = CONFIG_REGISTRY.filter((item) => item.scopes.includes('backend')).map((item) => item.key).sort();
  return `${header('js')}export const BACKEND_REGISTRY_SCHEMA_KEYS = Object.freeze(${JSON.stringify(keys, null, 2)});\n`;
}

function renderAdminUiSchema() {
  const categories = new Map();
  for (const item of CONFIG_REGISTRY.filter((entry) => entry.scopes.includes('backend'))) {
    const category = item.owner;
    const list = categories.get(category) || [];
    list.push({
      key: item.key,
      type: item.classification === 'secret' ? 'password' : item.valueType,
      isSecret: item.classification === 'secret',
      classification: item.classification,
      publicExposure: item.publicExposure,
      mutableAtRuntime: item.mutableAtRuntime,
      deprecatedAliases: item.deprecatedAliases,
    });
    categories.set(category, list);
  }
  return json({
    generatedBy: 'tools/config-registry/generate.mjs',
    categories: [...categories.entries()].map(([id, variables]) => ({
      id,
      name: id,
      variables: variables.sort((a, b) => a.key.localeCompare(b.key)),
    })),
  });
}

function renderK3sConfigMap() {
  const keys = CONFIG_REGISTRY.filter((item) => item.delivery.includes('k3s-configmap'))
    .map((item) => item.key)
    .sort();
  return `${header('yaml')}apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: blog-app-config-generated\n  namespace: blog\ndata:\n${keys.map((key) => `  ${key}: \"\"`).join('\n')}\n`;
}

function renderK3sSecretExample() {
  const keys = CONFIG_REGISTRY.filter((item) => item.delivery.includes('k3s-secret'))
    .map((item) => item.key)
    .sort();
  return `${header('yaml')}apiVersion: v1\nkind: Secret\nmetadata:\n  name: blog-app-secrets-generated\n  namespace: blog\ntype: Opaque\nstringData:\n${keys.map((key) => `  ${key}: \"<set-in-secret-manager>\"`).join('\n')}\n`;
}

function writeGenerated() {
  const errors = validateConfigRegistry();
  if (errors.length > 0) {
    throw new Error(`Config registry validation failed:\n${errors.join('\n')}`);
  }
  for (const [relativePath, render] of generatedFiles) {
    const target = path.join(repoRoot, relativePath);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, render());
  }
}

function checkGenerated() {
  const diffs = [];
  for (const [relativePath, render] of generatedFiles) {
    const target = path.join(repoRoot, relativePath);
    const expected = render();
    const actual = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
    if (actual !== expected) diffs.push(relativePath);
  }
  if (diffs.length > 0) {
    throw new Error(`Generated config artifacts are stale:\n${diffs.join('\n')}`);
  }
}

function main() {
  if (process.argv.includes('--check')) {
    checkGenerated();
    console.log('Config registry generated artifacts are current');
    return;
  }
  writeGenerated();
  console.log(`Generated ${generatedFiles.length} config registry artifacts`);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
