apiVersion: v1
kind: LimitRange
metadata:
  name: blog-default-limits
  namespace: blog
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 256Mi
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 100Gi
