apiVersion: v1
kind: Secret
metadata:
  name: ghcr-creds
  namespace: blog
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "your-github-username",
          "password": "your-ghcr-token"
        }
      }
    }
