/** These gates inspect recovered source and execute isolated production handlers.
 * They do not render React/Radix, call a server, or replace the project's Vitest/E2E gates. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import crypto from 'node:crypto';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),ts=require('typescript');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const text=f=>fs.readFileSync(path.join(root,f),'utf8');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const tree=s=>ts.createSourceFile('f.tsx',s,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
function walk(n,fn){fn(n);ts.forEachChild(n,c=>walk(c,fn));}
function canon(n,sf){const sc=ts.createScanner(ts.ScriptTarget.Latest,true,ts.LanguageVariant.JSX,n.getText(sf)),a=[];while(sc.scan()!==ts.SyntaxKind.EndOfFileToken)a.push(sc.getTokenText());return JSON.stringify(a);}
function signatures(s){const sf=tree(s),out={};walk(sf,n=>{if((ts.isVariableDeclaration(n)&&n.initializer||ts.isFunctionDeclaration(n))&&n.name&&ts.isIdentifier(n.name)){let jsx=false;walk(n,c=>{if(ts.isJsxElement(c)||ts.isJsxSelfClosingElement(c)||ts.isJsxFragment(c))jsx=true;});if(!jsx&&!out[n.name.text])out[n.name.text]=hash(canon(n,sf));}});return out;}
const contracts=JSON.parse(text('docs/ui-refactor/remaining-page-contracts.json'));
for(const [file,declarations]of Object.entries(contracts.declarations))test(`non-view declarations retained or explicitly amended: ${file}`,()=>{const actual=signatures(text(file));for(const [name,before]of Object.entries(declarations)){const amendment=contracts.amendments.find(x=>x.file===file&&x.name===name);if(amendment){assert.equal(amendment.before,before);assert.ok(amendment.reason);assert.equal(actual[name]??null,amendment.after);}else assert.equal(actual[name],before,name);}});
const E='frontend/src/components/features/admin/content/PostEditorWorkspace.tsx', B='frontend/src/components/features/admin/BotChatPanel.tsx', I='frontend/src/components/features/admin/AiImageGeneratorPanel.tsx';
function nodeNamed(src,name){const sf=tree(text(src));let result;walk(sf,n=>{if(!result&&(ts.isVariableDeclaration(n)||ts.isFunctionDeclaration(n))&&n.name?.getText(sf)===name)result=n;});assert.ok(result,`${src}: ${name}`);return{n:result,sf};}
function initializer(src,name){const {n,sf}=nodeNamed(src,name);let x=n.initializer;if(ts.isCallExpression(x)&&x.expression.getText(sf)==='useCallback')x=x.arguments[0];return x.getText(sf);}
function property(src,name,prop){const {n,sf}=nodeNamed(src,name),obj=n.initializer.arguments[0];return obj.properties.find(p=>p.name?.getText(sf)===prop).initializer.getText(sf);}
function compileExpr(expr,context={}){const js=ts.transpileModule('globalThis.result = ('+expr+');',{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText;const sandbox={...context};vm.runInNewContext(js,sandbox);return sandbox.result;}
function normalizers(){const sf=tree(text(E)),parts=[];for(const n of sf.statements)if(ts.isFunctionDeclaration(n)&&n.name?.text.startsWith('normalize'))parts.push(n.getText(sf));const ctx={URL,Intl};vm.runInNewContext(ts.transpileModule(parts.join('\n'),{compilerOptions:{target:ts.ScriptTarget.ES2020}}).outputText,ctx);return ctx;}
const reviewCtx={exports:{}};vm.runInNewContext(ts.transpileModule(text('frontend/src/components/features/admin/content/editorReview.ts'),{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText,reviewCtx);const review=reviewCtx.exports;
const draft=()=>({title:'Draft title',slug:'my-post',year:'2026',category:'General',tags:'A, B',coverImage:'/image.png',content:'## Body\ntext',published:true,updatedAt:'2026-09-06T10:00:00Z'});
for(const field of ['title','slug','year','category','tags','coverImage','content','published'])test(`review becomes stale when ${field} changes`,()=>{const a=draft(),b={...a,[field]:field==='published'?false:a[field]+'!'};assert.equal(review.isEditorReviewCurrent(review.editorReviewSignature(a),b),false);});
test('save timestamp alone does not invalidate review',()=>{const a=draft();assert.equal(review.isEditorReviewCurrent(review.editorReviewSignature(a),{...a,updatedAt:'later'}),true);});
for(const mode of ['publish','draft'])test(`actual mutation sends reviewed ${mode} payload, not live fields`,async()=>{let sent;const live={...draft(),title:'unreviewed title',content:'unreviewed body'};const fn=compileExpr(property(E,'createPr','mutationFn'),{...normalizers(),...live,createPostPR:async p=>(sent=p)});const snapshot=draft();await fn({mode,snapshot});assert.equal(sent.title,snapshot.title);assert.equal(sent.content,snapshot.content);assert.equal(sent.draft,mode==='draft');assert.deepEqual(Object.keys(sent).sort(),['content','draft','frontmatter','slug','title','year']);assert.deepEqual(Array.from(sent.frontmatter.tags),['A','B']);});
test('publish review respects existing unpublished flag',async()=>{let sent;await compileExpr(property(E,'createPr','mutationFn'),{...normalizers(),createPostPR:async p=>(sent=p)})({mode:'publish',snapshot:{...draft(),published:false}});assert.equal(sent.draft,true);assert.equal(sent.frontmatter.published,false);});
test('invalid year is rejected before API request',async()=>{let calls=0;const fn=compileExpr(property(E,'createPr','mutationFn'),{...normalizers(),createPostPR:async()=>calls++});await assert.rejects(fn({mode:'publish',snapshot:{...draft(),year:'not-year'}}));assert.equal(calls,0);});
function submitContext(overrides={}){const currentDraft=draft(),calls=[];return{...normalizers(),...review,currentDraft,submitReview:{mode:'publish',snapshot:{...currentDraft},signature:review.editorReviewSignature(currentDraft)},createPr:{isPending:false,mutate:x=>calls.push(x)},submitInFlight:{current:false},setSubmitFeedback:s=>calls.push(s),setSubmitReview:()=>{},calls,...overrides};}
test('review confirm rejects a stale document without a mutation',()=>{const c=submitContext({currentDraft:{...draft(),content:'modified'}});compileExpr(initializer(E,'submitReviewed'),c)();assert.equal(c.calls.length,1);assert.equal(typeof c.calls[0],'string');assert.equal(c.submitInFlight.current,false);});
test('review confirm copies snapshot and blocks same-render double submission',()=>{const c=submitContext(),fn=compileExpr(initializer(E,'submitReviewed'),c);fn();fn();assert.equal(c.calls.length,1);assert.notEqual(c.calls[0].snapshot,c.submitReview.snapshot);c.submitReview.snapshot.content='later';assert.equal(c.calls[0].snapshot.content,draft().content);});
test('absent or pending review never submits',()=>{for(const overrides of [{submitReview:null},{createPr:{isPending:true,mutate:()=>assert.fail('mutated')}},{submitInFlight:{current:true}}]){const c=submitContext(overrides);compileExpr(initializer(E,'submitReviewed'),c)();assert.equal(c.calls.length,0);}});
function storageContext(options={}){const events=[],writes=[],currentDraft=draft(),blocked={current:!!options.blocked};return{currentDraft,Date,DRAFT_STORAGE_KEY:'noblog.admin.postEditor.draft.v2',draftReadBlocked:blocked,window:{localStorage:{setItem:(k,v)=>{if(options.fail)throw Error('quota');writes.push([k,v]);}}},setDraftStatus:v=>events.push(['status',v]),setDraftError:v=>events.push(['error',v]),setDraftSavedAt:v=>events.push(['savedAt',v]),toast:v=>events.push(['toast',v]),events,writes};}
test('real local write failure preserves input and never reports saved',()=>{const c=storageContext({fail:true}),before=JSON.stringify(c.currentDraft);compileExpr(initializer(E,'saveDraft'),c)(true);assert.equal(c.events.at(-2)[1],'error');assert.ok(!c.events.some(e=>e[0]==='savedAt'||e[0]==='toast'));assert.equal(JSON.stringify(c.currentDraft),before);});
test('unreadable local draft is not overwritten by autosave',()=>{const c=storageContext({blocked:true});compileExpr(initializer(E,'saveDraft'),c)(false);assert.equal(c.writes.length,0);assert.equal(c.events.length,0);});
test('explicit local save clears unreadable-draft hold only after write succeeds',()=>{const c=storageContext({blocked:true});compileExpr(initializer(E,'saveDraft'),c)(true);assert.equal(c.writes.length,1);assert.equal(c.draftReadBlocked.current,false);assert.equal(JSON.parse(c.writes[0][1]).content,c.currentDraft.content);assert.ok(c.events.some(e=>e[0]==='status'&&e[1]==='saved'));});
test('failed local draft deletion retains saved timestamp and editor',()=>{const events=[];const ctx={window:{localStorage:{removeItem(){throw Error('denied');}}},DRAFT_STORAGE_KEY:'key',cancelPendingDraftAutosave:()=>{},setDraftError:x=>events.push(x),setDraftStatus:x=>events.push(x),setDraftSavedAt:()=>assert.fail('cleared saved time'),setClearDraftOpen:()=>assert.fail('closed dialog'),toast:()=>assert.fail('success')};compileExpr(initializer(E,'clearDraft'),ctx)();assert.equal(events.at(-1),'error');});
function proposalContext(stale=false){const effects=[];return{proposal:{signature:'approved',actions:[{type:'set_title',value:'new'}]},currentSignature:stale?'changed':'approved',proposalApplying:{current:false},applyActions:a=>{effects.push(a);return a.length;},setProposal:()=>{},setProposalFeedback:t=>effects.push(t),effects};}
test('agent proposal stale guard prevents all editor changes',()=>{const c=proposalContext(true);compileExpr(initializer(B,'acceptProposal'),c)();assert.equal(c.effects.length,1);assert.equal(typeof c.effects[0],'string');});
test('accepted proposal is applied exactly once under repeated click',()=>{const c=proposalContext(),fn=compileExpr(initializer(B,'acceptProposal'),c);fn();fn();assert.equal(c.effects.filter(Array.isArray).length,1);});
test('agent response does not automatically invoke editor setters',()=>{assert.doesNotMatch(initializer(B,'handleSend'),/applyActions\(/);assert.match(initializer(B,'handleSend'),/setProposal/);assert.match(text(B),/nativeEvent\.isComposing/);});
test('image thumbnail opens preview instead of inserting; ratio preserved',()=>{const s=text(I);assert.match(s,/onClick=\{\(\) => setPreviewImage/);assert.match(s,/onClick=\{\(\) => onInsertMarkdown/);assert.doesNotMatch(s,/object-cover/);assert.match(s,/<DialogDescription>/);});
test('actual image generation handler rejects a same-render duplicate request',async()=>{let release,calls=0;const flight={current:false},ctx={year:'2026',slug:'safe-post',title:'Post',prompt:'prompt',suggestedPrompt:'suggestion',count:'1',size:'1024x1024',quality:'medium',alt:'',AI_IMAGE_SLUG_PATTERN:/^[a-z-]+$/,INVALID_AI_IMAGE_SLUG_MESSAGE:'invalid',generationInFlight:flight,setIsGenerating:()=>{},setErrorMessage:()=>{},setItems:()=>{},toast:()=>{},buildFinalImagePrompt:x=>x,getErrorMessage:(e,f)=>e.message||f,generatePostImages:()=>{calls++;return new Promise(r=>release=r);}};const fn=compileExpr(initializer(I,'handleGenerate'),ctx);const first=fn();await fn();assert.equal(calls,1);release({items:[]});await first;assert.equal(flight.current,false);});
test('Insight panes stay mounted; one dedicated renderer owns display coordinates and edge dashes',()=>{
 const s=text('frontend/src/components/features/insight-workspace/InsightWorkspacePage.tsx'),e=text('frontend/src/components/features/insight-workspace/InsightExplorer.tsx');
 for(const id of ['insight-graph-pane','insight-inspector-pane'])assert.ok(s.includes('id=\''+id+'\''));
 assert.doesNotMatch(s,/<main/);assert.match(s,/<PaneSwitcher/);assert.match(s,/<InsightExplorer/);assert.match(e,/strokeDasharray/);assert.match(e,/layoutInsightNodes/);assert.doesNotMatch(e,/node\.x\s*=|node\.y\s*=/);
});
test('editor panes stay mounted; original local draft key retained',()=>{const s=text(E);assert.match(s,/noblog\.admin\.postEditor\.draft\.v2/);assert.doesNotMatch(s,/\{editorMode !== 'preview' &&/);assert.doesNotMatch(s,/\{editorMode !== 'write' &&/);});
test('admin retains all nine real section IDs and has a labelled mobile selector',()=>{const s=text('frontend/src/pages/admin/AdminDashboard.tsx');for(const id of ['health','rag','analytics','logs','content','ai','config','secrets','workers'])assert.match(s,new RegExp("id: '"+id+"'"));assert.match(s,/<select/);assert.match(s,/<label/);assert.doesNotMatch(s,/<main/);});
test('error components use original presets rather than invented retry success',()=>{const s=text('frontend/src/pages/public/errors/ErrorStatusPage.tsx');assert.match(s,/ui-error-page/);assert.doesNotMatch(s,/setTimeout|localStorage\.setItem/);});

test('editor tools keep chat and generation state mounted while inactive tabs are hidden',()=>{const s=text(E);for(const id of ['assistant','images','assets'])assert.match(s,new RegExp("<TabsContent forceMount value='"+id+"'"));assert.match(text('frontend/src/styles/ui-editor.css'),/\[role='tabpanel'\]\[data-state='inactive'\]/);});
