#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(__filename), '..', '..');
const baselinePath = path.join(repoRoot, 'docs/generated/config-inventory.baseline.json');
const summaryPath = path.join(repoRoot, 'docs/generated/config-inventory.summary.md');

const SOURCE_CONFIG = [
  {
    source: 'backend.process-env',
    roots: ['backend/src', 'backend/scripts', 'scripts'],
    patterns: [/process\.env\.([A-Z][A-Z0-9_]*)/g],
  },
  {
    source: 'frontend.import-meta-env',
    roots: ['frontend/src', 'frontend/scripts'],
    patterns: [/import\.meta\.env\.([A-Z][A-Z0-9_]*)/g],
  },
  {
    source: 'worker.env-binding',
    roots: ['workers'],
    patterns: [/\b(?:c\.)?env\.([A-Z][A-Z0-9_]*)/g],
  },
  {
    source: 'github.secrets',
    roots: ['.github/workflows'],
    patterns: [/secrets\.([A-Z][A-Z0-9_]*)/g],
  },
  {
    source: 'shared.contracts',
    roots: ['shared/src/contracts'],
    patterns: [/\bkey:\s*['"]([A-Z][A-Z0-9_]*)['"]/g, /['"]([A-Z][A-Z0-9_]*)['"]/g],
  },
];

const YAML_KEY_PATTERN = /^\s{2}([A-Z][A-Z0-9_]*):\s*/gm;

function listFiles(root, result = []) {
  const fullRoot = path.join(repoRoot, root);
  if (!fs.existsSync(fullRoot)) return result;
  for (const dirent of fs.readdirSync(fullRoot, { withFileTypes: true })) {
    const fullPath = path.join(fullRoot, dirent.name);
    const relativePath = path.relative(repoRoot, fullPath);
    if (dirent.isDirectory()) {
      if (['node_modules', 'dist', '.wrangler', '.turbo', 'coverage'].includes(dirent.name)) continue;
      listFiles(relativePath, result);
    } else if (/\.(?:js|mjs|cjs|ts|tsx|json|ya?ml|toml|sh)$/.test(dirent.name)) {
      result.push(relativePath);
    }
  }
  return result;
}

function addOccurrence(map, key, source, file, line) {
  if (!key || key.length < 2) return;
  const entry = map.get(key) || { key, occurrences: [] };
  entry.occurrences.push({ source, file, line });
  map.set(key, entry);
}

function lineForOffset(text, offset) {
  return text.slice(0, offset).split('\n').length;
}

function collectSource(map, sourceConfig) {
  const files = [...new Set(sourceConfig.roots.flatMap((root) => listFiles(root)))];
  for (const file of files) {
    const fullPath = path.join(repoRoot, file);
    const text = fs.readFileSync(fullPath, 'utf8');
    for (const pattern of sourceConfig.patterns) {
      pattern.lastIndex = 0;
      let match;
      while ((match = pattern.exec(text)) !== null) {
        addOccurrence(map, match[1], sourceConfig.source, file, lineForOffset(text, match.index));
      }
    }
  }
}

function collectK3s(map) {
  const files = ['k3s/configmap.yaml', 'k3s/secret-example.yaml'];
  for (const file of files) {
    const fullPath = path.join(repoRoot, file);
    if (!fs.existsSync(fullPath)) continue;
    const text = fs.readFileSync(fullPath, 'utf8');
    YAML_KEY_PATTERN.lastIndex = 0;
    let match;
    while ((match = YAML_KEY_PATTERN.exec(text)) !== null) {
      addOccurrence(
        map,
        match[1],
        file.includes('secret') ? 'k3s.secret-example' : 'k3s.configmap',
        file,
        lineForOffset(text, match.index),
      );
    }
  }
}

export function collectInventory() {
  const map = new Map();
  for (const sourceConfig of SOURCE_CONFIG) collectSource(map, sourceConfig);
  collectK3s(map);

  const keys = [...map.values()]
    .map((item) => ({
      key: item.key,
      occurrences: item.occurrences.sort((a, b) =>
        a.file === b.file ? a.line - b.line : a.file.localeCompare(b.file),
      ),
    }))
    .sort((a, b) => a.key.localeCompare(b.key));

  return {
    generatedAt: new Date().toISOString(),
    source: 'tools/config-inventory/index.mjs',
    valueCollection: false,
    totalKeys: keys.length,
    keys,
  };
}

function stableInventory(inventory) {
  return {
    ...inventory,
    generatedAt: '<generated>',
  };
}

function renderSummary(inventory) {
  const bySource = new Map();
  for (const item of inventory.keys) {
    for (const occurrence of item.occurrences) {
      bySource.set(occurrence.source, (bySource.get(occurrence.source) || 0) + 1);
    }
  }

  const lines = [
    '# Config Inventory Summary',
    '',
    '<!-- DO NOT EDIT: generated by tools/config-inventory/index.mjs -->',
    '',
    `Total unique keys: ${inventory.totalKeys}`,
    '',
    '| Source | Occurrences |',
    '| --- | ---: |',
  ];
  for (const [source, count] of [...bySource.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`| ${source} | ${count} |`);
  }
  lines.push('', '## Keys', '');
  for (const item of inventory.keys) {
    const sources = [...new Set(item.occurrences.map((occurrence) => occurrence.source))].sort();
    lines.push(`- \`${item.key}\` (${sources.join(', ')})`);
  }
  lines.push('');
  return lines.join('\n');
}

function writeInventory(inventory) {
  fs.mkdirSync(path.dirname(baselinePath), { recursive: true });
  fs.writeFileSync(baselinePath, `${JSON.stringify(inventory, null, 2)}\n`);
  fs.writeFileSync(summaryPath, renderSummary(inventory));
}

function checkInventory(inventory) {
  if (!fs.existsSync(baselinePath)) {
    throw new Error(`Missing baseline: ${path.relative(repoRoot, baselinePath)}`);
  }
  const baseline = JSON.parse(fs.readFileSync(baselinePath, 'utf8'));
  const expected = JSON.stringify(stableInventory(baseline), null, 2);
  const actual = JSON.stringify(stableInventory(inventory), null, 2);
  if (expected !== actual) {
    throw new Error('Config inventory drift detected. Run npm run config:inventory:write.');
  }
}

function main() {
  const args = new Set(process.argv.slice(2));
  const inventory = collectInventory();
  if (args.has('--write')) {
    writeInventory(inventory);
    console.log(`Wrote ${path.relative(repoRoot, baselinePath)} (${inventory.totalKeys} keys)`);
    return;
  }
  if (args.has('--check')) {
    checkInventory(inventory);
    console.log(`Config inventory matches baseline (${inventory.totalKeys} keys)`);
    return;
  }
  console.log(JSON.stringify(inventory, null, 2));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
