name = "ai-serve"
main = "src/index.ts"
compatibility_date = "2025-10-21"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGINS = "https://noblog.nodove.com"
# Optional: fixed provider/model for server defaults
DEFAULT_PROVIDER = "openai"
DEFAULT_MODEL = "gpt-4.1"

[[routes]]
pattern = "ai-serve.nodove.com/session*"
zone_name = "nodove.com"
