// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	ENV: "development" | "production";
	ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:4173,http://localhost:8080,http://localhost:8081,https://noblog.nodove.com,https://blog.nodove.com,https://blog-test.nodove.com" | "https://noblog.nodove.com,https://blog.nodove.com,https://blog-test.nodove.com";
	ASSETS_BASE_URL: "https://assets-b.nodove.com";
	API_BASE_URL: "https://api.nodove.com";
	R2: R2Bucket;
	DB: D1Database;
}
