#!/usr/bin/env python3
"""
fix_codelines.py
Replaces wrong _codeLines in algo-060 to algo-100 HTML files
with the correct Python code matching each file's actual algorithm.
"""

import re
import os
import json
import glob

# Correct Python code for each algorithm file
# Keys are zero-padded 3-digit numbers matching the file name
CORRECT_CODE = {
    "060": [
        "def flatten(root):",
        "    if not root: return",
        "    flatten(root.left)",
        "    flatten(root.right)",
        "    right = root.right",
        "    root.right = root.left",
        "    root.left = None",
        "    cur = root",
        "    while cur.right: cur = cur.right",
        "    cur.right = right",
    ],
    "061": [
        "class MinHeap:",
        "    def push(self, val):",
        "        self.heap.append(val)",
        "        self._sift_up(len(self.heap)-1)",
        "    def pop(self):",
        "        self.heap[0], self.heap[-1] = self.heap[-1], self.heap[0]",
        "        val = self.heap.pop()",
        "        self._sift_down(0)",
        "        return val",
    ],
    "062": [
        "def top_k_frequent(nums, k):",
        "    count = {}",
        "    for n in nums:",
        "        count[n] = count.get(n, 0) + 1",
        "    import heapq",
        "    return heapq.nlargest(k, count, key=count.get)",
    ],
    "063": [
        "class MedianFinder:",
        "    def __init__(self):",
        "        self.lo = []  # max-heap (negated)",
        "        self.hi = []  # min-heap",
        "    def addNum(self, num):",
        "        heapq.heappush(self.lo, -num)",
        "        heapq.heappush(self.hi, -heapq.heappop(self.lo))",
        "        if len(self.lo) < len(self.hi):",
        "            heapq.heappush(self.lo, -heapq.heappop(self.hi))",
        "    def findMedian(self):",
        "        if len(self.lo) > len(self.hi): return -self.lo[0]",
        "        return (-self.lo[0] + self.hi[0]) / 2",
    ],
    "064": [
        "def min_meeting_rooms(intervals):",
        "    import heapq",
        "    intervals.sort()",
        "    heap = []",
        "    for start, end in intervals:",
        "        if heap and heap[0] <= start:",
        "            heapq.heapreplace(heap, end)",
        "        else:",
        "            heapq.heappush(heap, end)",
        "    return len(heap)",
    ],
    "065": [
        "# Graph Representation",
        "# Adjacency List",
        "graph = {",
        "    0: [1, 2],",
        "    1: [0, 3],",
        "    2: [0, 3],",
        "    3: [1, 2],",
        "}",
        "# Adjacency Matrix",
        "matrix = [[0,1,1,0],[1,0,0,1],[1,0,0,1],[0,1,1,0]]",
    ],
    "066": [
        "def bfs(graph, start):",
        "    from collections import deque",
        "    visited = set([start])",
        "    queue = deque([start])",
        "    while queue:",
        "        node = queue.popleft()",
        "        for nei in graph[node]:",
        "            if nei not in visited:",
        "                visited.add(nei)",
        "                queue.append(nei)",
    ],
    "067": [
        "def dfs(graph, node, visited=None):",
        "    if visited is None: visited = set()",
        "    visited.add(node)",
        "    for nei in graph[node]:",
        "        if nei not in visited:",
        "            dfs(graph, nei, visited)",
        "    return visited",
    ],
    "068": [
        "def is_bipartite(graph):",
        "    color = {}",
        "    for start in range(len(graph)):",
        "        if start in color: continue",
        "        queue = [start]",
        "        color[start] = 0",
        "        while queue:",
        "            node = queue.pop()",
        "            for nei in graph[node]:",
        "                if nei not in color:",
        "                    color[nei] = 1 - color[node]",
        "                    queue.append(nei)",
        "                elif color[nei] == color[node]:",
        "                    return False",
        "    return True",
    ],
    "069": [
        "def clone_graph(node):",
        "    if not node: return None",
        "    visited = {}",
        "    def dfs(n):",
        "        if n in visited: return visited[n]",
        "        clone = Node(n.val)",
        "        visited[n] = clone",
        "        for nei in n.neighbors:",
        "            clone.neighbors.append(dfs(nei))",
        "        return clone",
        "    return dfs(node)",
    ],
    "070": [
        "def word_ladder(begin, end, word_list):",
        "    from collections import deque",
        "    word_set = set(word_list)",
        "    queue = deque([(begin, 1)])",
        "    while queue:",
        "        word, length = queue.popleft()",
        "        for i in range(len(word)):",
        "            for c in 'abcdefghijklmnopqrstuvwxyz':",
        "                nw = word[:i] + c + word[i+1:]",
        "                if nw == end: return length + 1",
        "                if nw in word_set:",
        "                    word_set.remove(nw)",
        "                    queue.append((nw, length+1))",
        "    return 0",
    ],
    "071": [
        "def dijkstra(graph, src):",
        "    import heapq",
        "    dist = {node: float('inf') for node in graph}",
        "    dist[src] = 0",
        "    heap = [(0, src)]",
        "    while heap:",
        "        d, u = heapq.heappop(heap)",
        "        if d > dist[u]: continue",
        "        for v, w in graph[u]:",
        "            if dist[u] + w < dist[v]:",
        "                dist[v] = dist[u] + w",
        "                heapq.heappush(heap, (dist[v], v))",
        "    return dist",
    ],
    "072": [
        "def bellman_ford(n, edges, src):",
        "    dist = [float('inf')] * n",
        "    dist[src] = 0",
        "    for _ in range(n - 1):",
        "        for u, v, w in edges:",
        "            if dist[u] + w < dist[v]:",
        "                dist[v] = dist[u] + w",
        "    # Check negative cycles",
        "    for u, v, w in edges:",
        "        if dist[u] + w < dist[v]:",
        "            return None  # negative cycle",
        "    return dist",
    ],
    "073": [
        "def floyd_warshall(dist):",
        "    n = len(dist)",
        "    for k in range(n):",
        "        for i in range(n):",
        "            for j in range(n):",
        "                if dist[i][k] + dist[k][j] < dist[i][j]:",
        "                    dist[i][j] = dist[i][k] + dist[k][j]",
        "    return dist",
    ],
    "074": [
        "def topo_sort(n, edges):",
        "    from collections import deque",
        "    graph = [[] for _ in range(n)]",
        "    indegree = [0] * n",
        "    for u, v in edges:",
        "        graph[u].append(v)",
        "        indegree[v] += 1",
        "    queue = deque(i for i in range(n) if indegree[i] == 0)",
        "    order = []",
        "    while queue:",
        "        node = queue.popleft()",
        "        order.append(node)",
        "        for nei in graph[node]:",
        "            indegree[nei] -= 1",
        "            if indegree[nei] == 0:",
        "                queue.append(nei)",
        "    return order if len(order) == n else []",
    ],
    "075": [
        "def kruskal(n, edges):",
        "    edges.sort(key=lambda e: e[2])",
        "    parent = list(range(n))",
        "    def find(x):",
        "        while parent[x] != x:",
        "            parent[x] = parent[parent[x]]",
        "            x = parent[x]",
        "        return x",
        "    mst, cost = [], 0",
        "    for u, v, w in edges:",
        "        pu, pv = find(u), find(v)",
        "        if pu != pv:",
        "            parent[pu] = pv",
        "            mst.append((u, v, w))",
        "            cost += w",
        "    return mst, cost",
    ],
    "076": [
        "def prim(n, graph):",
        "    import heapq",
        "    visited = set()",
        "    heap = [(0, 0)]",
        "    cost = 0",
        "    while heap:",
        "        w, u = heapq.heappop(heap)",
        "        if u in visited: continue",
        "        visited.add(u)",
        "        cost += w",
        "        for v, weight in graph[u]:",
        "            if v not in visited:",
        "                heapq.heappush(heap, (weight, v))",
        "    return cost",
    ],
    "077": [
        "def kosaraju_scc(n, edges):",
        "    graph = [[] for _ in range(n)]",
        "    rev = [[] for _ in range(n)]",
        "    for u, v in edges:",
        "        graph[u].append(v)",
        "        rev[v].append(u)",
        "    visited, order = set(), []",
        "    def dfs1(u):",
        "        visited.add(u)",
        "        for v in graph[u]:",
        "            if v not in visited: dfs1(v)",
        "        order.append(u)",
        "    for i in range(n):",
        "        if i not in visited: dfs1(i)",
        "    visited.clear()",
        "    sccs = []",
        "    def dfs2(u, comp):",
        "        visited.add(u)",
        "        comp.append(u)",
        "        for v in rev[u]:",
        "            if v not in visited: dfs2(v, comp)",
        "    for u in reversed(order):",
        "        if u not in visited:",
        "            comp = []",
        "            dfs2(u, comp)",
        "            sccs.append(comp)",
        "    return sccs",
    ],
    "078": [
        "def network_delay(times, n, k):",
        "    import heapq",
        "    graph = {i: [] for i in range(1, n+1)}",
        "    for u, v, w in times:",
        "        graph[u].append((v, w))",
        "    dist = {i: float('inf') for i in range(1, n+1)}",
        "    dist[k] = 0",
        "    heap = [(0, k)]",
        "    while heap:",
        "        d, u = heapq.heappop(heap)",
        "        if d > dist[u]: continue",
        "        for v, w in graph[u]:",
        "            if dist[u] + w < dist[v]:",
        "                dist[v] = dist[u] + w",
        "                heapq.heappush(heap, (dist[v], v))",
        "    mx = max(dist.values())",
        "    return mx if mx < float('inf') else -1",
    ],
    "079": [
        "def valid_path(n, edges, src, dst):",
        "    parent = list(range(n))",
        "    def find(x):",
        "        while parent[x] != x:",
        "            parent[x] = parent[parent[x]]",
        "            x = parent[x]",
        "        return x",
        "    for u, v in edges:",
        "        pu, pv = find(u), find(v)",
        "        if pu != pv:",
        "            parent[pu] = pv",
        "    return find(src) == find(dst)",
    ],
    "080": [
        "def cheapest_flights(n, flights, src, dst, k):",
        "    import heapq",
        "    graph = [[] for _ in range(n)]",
        "    for u, v, w in flights:",
        "        graph[u].append((v, w))",
        "    heap = [(0, src, 0)]",
        "    visited = {}",
        "    while heap:",
        "        cost, u, stops = heapq.heappop(heap)",
        "        if u == dst: return cost",
        "        if stops > k: continue",
        "        if visited.get(u, float('inf')) <= stops: continue",
        "        visited[u] = stops",
        "        for v, w in graph[u]:",
        "            heapq.heappush(heap, (cost+w, v, stops+1))",
        "    return -1",
    ],
    "081": [
        "def fib(n):",
        "    if n <= 1: return n",
        "    a, b = 0, 1",
        "    for _ in range(2, n+1):",
        "        a, b = b, a + b",
        "    return b",
    ],
    "082": [
        "def climb_stairs(n):",
        "    if n <= 2: return n",
        "    a, b = 1, 2",
        "    for _ in range(3, n+1):",
        "        a, b = b, a + b",
        "    return b",
    ],
    "083": [
        "def coin_change(coins, amount):",
        "    dp = [float('inf')] * (amount + 1)",
        "    dp[0] = 0",
        "    for coin in coins:",
        "        for i in range(coin, amount + 1):",
        "            dp[i] = min(dp[i], dp[i - coin] + 1)",
        "    return dp[amount] if dp[amount] != float('inf') else -1",
    ],
    "084": [
        "def knapsack(weights, values, W):",
        "    n = len(weights)",
        "    dp = [[0]*(W+1) for _ in range(n+1)]",
        "    for i in range(1, n+1):",
        "        for w in range(W+1):",
        "            dp[i][w] = dp[i-1][w]",
        "            if weights[i-1] <= w:",
        "                dp[i][w] = max(dp[i][w], dp[i-1][w-weights[i-1]]+values[i-1])",
        "    return dp[n][W]",
    ],
    "085": [
        "def longest_increasing_subsequence(nums):",
        "    dp = []",
        "    for n in nums:",
        "        lo, hi = 0, len(dp)",
        "        while lo < hi:",
        "            mid = (lo+hi)//2",
        "            if dp[mid] < n: lo = mid+1",
        "            else: hi = mid",
        "        if lo == len(dp): dp.append(n)",
        "        else: dp[lo] = n",
        "    return len(dp)",
    ],
    "086": [
        "def longest_common_subsequence(s, t):",
        "    m, n = len(s), len(t)",
        "    dp = [[0]*(n+1) for _ in range(m+1)]",
        "    for i in range(1, m+1):",
        "        for j in range(1, n+1):",
        "            if s[i-1]==t[j-1]: dp[i][j] = dp[i-1][j-1]+1",
        "            else: dp[i][j] = max(dp[i-1][j], dp[i][j-1])",
        "    return dp[m][n]",
    ],
    "087": [
        "def edit_distance(s, t):",
        "    m, n = len(s), len(t)",
        "    dp = list(range(n+1))",
        "    for i in range(1, m+1):",
        "        ndp = [i] + [0]*n",
        "        for j in range(1, n+1):",
        "            if s[i-1]==t[j-1]: ndp[j] = dp[j-1]",
        "            else: ndp[j] = 1 + min(dp[j], ndp[j-1], dp[j-1])",
        "        dp = ndp",
        "    return dp[n]",
    ],
    "088": [
        "def rob(nums):",
        "    prev2 = prev1 = 0",
        "    for n in nums:",
        "        prev2, prev1 = prev1, max(prev1, prev2+n)",
        "    return prev1",
    ],
    "089": [
        "def unique_paths(m, n):",
        "    dp = [[1]*n for _ in range(m)]",
        "    for i in range(1, m):",
        "        for j in range(1, n):",
        "            dp[i][j] = dp[i-1][j] + dp[i][j-1]",
        "    return dp[m-1][n-1]",
    ],
    "090": [
        "def word_break(s, word_dict):",
        "    n = len(s)",
        "    dp = [False]*(n+1); dp[0] = True",
        "    for i in range(1, n+1):",
        "        for w in word_dict:",
        "            if dp[i-len(w)] and s[i-len(w):i]==w:",
        "                dp[i] = True; break",
        "    return dp[n]",
    ],
    "091": [
        "class TrieNode:",
        "    def __init__(self):",
        "        self.children = {}",
        "        self.is_end = False",
        "class Trie:",
        "    def insert(self, word):",
        "        node = self.root",
        "        for ch in word:",
        "            if ch not in node.children:",
        "                node.children[ch] = TrieNode()",
        "            node = node.children[ch]",
        "        node.is_end = True",
        "    def search(self, word):",
        "        node = self.root",
        "        for ch in word:",
        "            if ch not in node.children: return False",
        "            node = node.children[ch]",
        "        return node.is_end",
    ],
    "092": [
        "class UnionFind:",
        "    def __init__(self, n):",
        "        self.parent = list(range(n))",
        "        self.rank = [0] * n",
        "    def find(self, x):",
        "        while self.parent[x] != x:",
        "            self.parent[x] = self.parent[self.parent[x]]",
        "            x = self.parent[x]",
        "        return x",
        "    def union(self, x, y):",
        "        px, py = self.find(x), self.find(y)",
        "        if px == py: return False",
        "        if self.rank[px] < self.rank[py]: px, py = py, px",
        "        self.parent[py] = px",
        "        if self.rank[px] == self.rank[py]: self.rank[px] += 1",
        "        return True",
    ],
    "093": [
        "class SegmentTree:",
        "    def __init__(self, arr):",
        "        self.n = len(arr)",
        "        self.tree = [0] * (4 * self.n)",
        "        self._build(arr, 1, 0, self.n-1)",
        "    def _build(self, arr, node, start, end):",
        "        if start == end:",
        "            self.tree[node] = arr[start]",
        "        else:",
        "            mid = (start+end)//2",
        "            self._build(arr, 2*node, start, mid)",
        "            self._build(arr, 2*node+1, mid+1, end)",
        "            self.tree[node] = self.tree[2*node] + self.tree[2*node+1]",
        "    def query(self, l, r):",
        "        return self._query(1, 0, self.n-1, l, r)",
    ],
    "094": [
        "def activity_selection(activities):",
        "    activities.sort(key=lambda x: x[1])",
        "    selected = [activities[0]]",
        "    last_end = activities[0][1]",
        "    for start, end in activities[1:]:",
        "        if start >= last_end:",
        "            selected.append((start, end))",
        "            last_end = end",
        "    return selected",
    ],
    "095": [
        "import heapq",
        "def huffman(freq):",
        "    heap = [[w, [sym, '']] for sym, w in freq.items()]",
        "    heapq.heapify(heap)",
        "    while len(heap) > 1:",
        "        lo = heapq.heappop(heap)",
        "        hi = heapq.heappop(heap)",
        "        for pair in lo[1:]: pair[1] = '0' + pair[1]",
        "        for pair in hi[1:]: pair[1] = '1' + pair[1]",
        "        heapq.heappush(heap, [lo[0]+hi[0]] + lo[1:] + hi[1:])",
        "    return dict(sorted(heapq.heappop(heap)[1:], key=lambda p: len(p[1])))",
    ],
    "096": [
        "# Bit Manipulation",
        "def count_set_bits(n):",
        "    count = 0",
        "    while n:",
        "        n &= n - 1",
        "        count += 1",
        "    return count",
        "def is_power_of_two(n):",
        "    return n > 0 and (n & (n-1)) == 0",
        "def get_bit(n, i): return (n >> i) & 1",
        "def set_bit(n, i): return n | (1 << i)",
        "def clear_bit(n, i): return n & ~(1 << i)",
    ],
    "097": [
        "def count_bits(n):",
        "    dp = [0] * (n + 1)",
        "    for i in range(1, n + 1):",
        "        dp[i] = dp[i >> 1] + (i & 1)",
        "    return dp",
    ],
    "098": [
        "def matrix_chain(dims):",
        "    n = len(dims) - 1",
        "    dp = [[0]*n for _ in range(n)]",
        "    for length in range(2, n+1):",
        "        for i in range(n - length + 1):",
        "            j = i + length - 1",
        "            dp[i][j] = float('inf')",
        "            for k in range(i, j):",
        "                cost = dp[i][k] + dp[k+1][j] + dims[i]*dims[k+1]*dims[j+1]",
        "                dp[i][j] = min(dp[i][j], cost)",
        "    return dp[0][n-1]",
    ],
    "099": [
        "def maximal_square(matrix):",
        "    if not matrix: return 0",
        "    m, n = len(matrix), len(matrix[0])",
        "    dp = [[0]*n for _ in range(m)]",
        "    max_side = 0",
        "    for i in range(m):",
        "        for j in range(n):",
        "            if matrix[i][j] == '1':",
        "                if i == 0 or j == 0:",
        "                    dp[i][j] = 1",
        "                else:",
        "                    dp[i][j] = min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]) + 1",
        "                max_side = max(max_side, dp[i][j])",
        "    return max_side * max_side",
    ],
    "100": [
        "class LRUCache:",
        "    def __init__(self, capacity, ttl):",
        "        from collections import OrderedDict",
        "        self.cap = capacity",
        "        self.ttl = ttl",
        "        self.cache = OrderedDict()",
        "        self.time = {}",
        "    def get(self, key, now):",
        "        if key not in self.cache: return -1",
        "        if now - self.time[key] > self.ttl:",
        "            del self.cache[key], self.time[key]",
        "            return -1",
        "        self.cache.move_to_end(key)",
        "        return self.cache[key]",
        "    def put(self, key, val, now):",
        "        if key in self.cache: self.cache.move_to_end(key)",
        "        self.cache[key] = val",
        "        self.time[key] = now",
        "        if len(self.cache) > self.cap:",
        "            self.cache.popitem(last=False)",
    ],
}


def fix_codelines_in_file(filepath: str, num: str) -> bool:
    """Replace _codeLines in a single HTML file with the correct code."""
    correct = CORRECT_CODE.get(num)
    if not correct:
        return False

    with open(filepath, "r", encoding="utf-8") as f:
        html = f.read()

    # Find and replace const _codeLines = [...];
    pattern = r"const _codeLines = \[.*?\];"
    new_val = "const _codeLines = " + json.dumps(correct, ensure_ascii=False) + ";"
    new_html, n = re.subn(pattern, new_val, html, flags=re.DOTALL)

    if n == 0:
        print(f"  SKIP {os.path.basename(filepath)}: _codeLines not found")
        return False

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(new_html)
    return True


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    total_fixed = 0
    total_skip = 0

    for num in sorted(CORRECT_CODE.keys()):
        pattern = os.path.join(script_dir, f"algo-{num}-*.html")
        files = [f for f in glob.glob(pattern) if not f.endswith(".bak")]
        if not files:
            print(f"  NOT FOUND: algo-{num}-*.html")
            continue
        filepath = files[0]
        fname = os.path.basename(filepath)
        fixed = fix_codelines_in_file(filepath, num)
        if fixed:
            print(f"  FIXED {fname}")
            total_fixed += 1
        else:
            total_skip += 1

    print(f"\nDone: {total_fixed} files fixed, {total_skip} skipped.")


if __name__ == "__main__":
    main()
