name: Deploy ai-check-gateway

on:
  push:
    branches: [ main ]
    paths:
      - 'workers/ai-check-gateway/**'
      - '.github/workflows/deploy-ai-check-gateway.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: workers/package-lock.json

      - name: Install Wrangler 4
        working-directory: workers
        run: npm install --save-dev wrangler@4

      - name: Deploy ai-check-gateway (production)
        working-directory: workers/ai-check-gateway
        run: npx wrangler deploy --env production

      - name: Deployment summary
        run: |
          echo "✅ ai-check-gateway deployed successfully"
          echo "🌍 Route configured in workers/ai-check-gateway/wrangler.toml"
